name: learn-github-actions
on: [push]
jobs:
  test-java:
    strategy:
      matrix:
        test_tag: ${{ fromJSON(github.event.inputs.test_tags) }}
        deploy_id: [ '${{ github.event.inputs.deploy_id }}' ]
        deploy_group: [ '${{ github.event.inputs.deploy_group }}' ]
        project: [ '${{ github.event.inputs.project }}' ]
        ref: [ '${{ github.event.inputs.ref }}' ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test run
        run: mvn --batch-mode --update-snapshots verify